ap:
  host: "192.168.10.122"
  port: 22
  username: "root"
  password: "openwifi"
  # key_path: "/home/user/.ssh/id_rsa"
  interface: "sdr0"

ubuntu:
  server_ip: "192.168.10.1"

iperf_servers:
  ports: [5201, 5202, 5203]

sampling:
  interval_sec: 1

capture:
  phy: "phy0"
  monitor_iface: "mon0"
  packet_count: 1000
  pcap_dir: "data/pcaps"
  timeout_sec: 60
